apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy19
  labels:
    app: autodeploy19
  namespace: namespace-workflow-1708350684455
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy19
  template:
    metadata:
      labels:
        app: autodeploy19
    spec:
      containers:
        - name: autodeploy19
          image: acrworkflow1708350684455.azurecr.io/image-workflow-1708350684455:latest
          ports:
            - containerPort: 5000